const TableData = [
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
  {
    Title: 'Classroom Instructions',
    Project: '[Academic Institution Sample]',
    Created: 'Created',
    Assigned: 'Employee',
    Status: 'Not Started',
    Priority: 'Low',
  },
]

export default TableData
